# Generated by Django 4.2 on 2024-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffs_app', '0002_server_shift_remove_project_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
