# Generated by Django 4.2 on 2024-04-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffs_app', '0004_shift_position_alter_shift_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='server',
        ),
        migrations.AddField(
            model_name='shift',
            name='username',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.DeleteModel(
            name='Server',
        ),
    ]
