# Generated by Django 4.2 on 2024-04-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buffs_app', '0005_remove_shift_server_shift_username_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='Taken_By',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
